
title: Opendoc Theme
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: index
  doctype: bare
kramdown:
  auto_id_stripping: true
environment: DEV
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://opendoc.sg
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo.png
