
title: Opendoc Theme
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-github-metadata
section_order:
  - Introduction
  - Getting started
repository: opendocsg/opendoc-theme
kramdown:
  auto_id_stripping: true
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
styling_options:
  primary_brand_color: '#990921'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5b6a6673d7059a000ff7f7c7
